name: General Tests
on: [push, pull_request]
jobs:
  # lint:
  #   name: ESLint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2

  #     - name: Install Node v16
  #       uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c # renovate: tag=v2
  #       with:
  #         node-version: 16

  #     - name: Install dependencies
  #       run: yarn install

  #     - name: Run ESLint
  #       run: yarn run lint
  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3

      - name: Install Node v16
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # tag=v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: TypeScript Compiler
        run: yarn run build
